version: '3.8'
services:
  app:
    # Build with the development Dockerfile
    build:
      context: .
      dockerfile: Dockerfile.dev
    # Mount code for live editing
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - PORT=3000
    command: npm start

# commands to run
# docker-compose up
